version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: learncode@123
      POSTGRES_DB: learncode
    ports:
      - "54321:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" 
    command: ["redis-server", "--requirepass", "redisPassword", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  # web:
  #   image: nginx
  #   volumes:
  #   - ./templates:/etc/nginx/templates
  #   ports:
  #   - "8081:80"
  #   environment:
  #   - NGINX_HOST=foobar.com
  #   - NGINX_PORT=80

volumes:
  redis_data:
    driver: local 